### ISSUE TITLE
[Bug]: Config files ending in ".yml" are deprecated, please use ".yaml" instead

### ISSUE THREAD

**Issue by ll7** [una-auxme/paf#195]
### Current Behavior

```shell
/paf23$ b5 install
b5 1.4.1
Found project path (/home/luttkule/git/paf23)
Found Taskfile (Taskfile)
Found config (config.yml, config.local.yml)
Config files ending in ".yml" are deprecated, please use ".yaml" instead
```

**Comment by JulianTrommer** [comment]
GitHub Actions only support .yml files, these should not be changed.

**Comment by ll7** [comment]
> GitHub Actions only support .yml files, these should not be changed.

Okay, I will close this issue. We only have a few broken links in the documentation due to changing the `docker-compose` structure.
