### ISSUE TITLE
[Feature]: Should `doc/02_development/04_coding_style.md` be simplified to: code according to pylint

### ISSUE THREAD

**Issue by ll7** [una-auxme/paf#252]
### Description

This document appears to be a lot of copy and paste. It is not clear where this document diverges from any standard formatting guideline. Why not use `pylint` instead, as this is the standard linter already used in the project?

### Definition of Done

Resolve this discussion with a final decision.

**Comment by JulianTrommer** [comment]
This is already covered with Flake8 and will be fixed with #289
