### ISSUE TITLE
[Feature]: Create a document for best practices during the development phase

### ISSUE THREAD

**Issue by ll7** [una-auxme/paf#254]
### Description

Developing in paf23 is not easy. Simplify the first steps by presenting good guidelines on what to do.

### Definition of Done

- [ ] Document for frist steps

**Comment by ll7** [comment]
- [ ] Create in interactive container where assisted development is possible.
- [ ] Code Completion
- [ ] Interactive runs, etc.

**Comment by JulianTrommer** [comment]
VSCode extensions need to be installed one time in the dev container.
We need to document this.
