### ISSUE TITLE
[Feature]: Rename repository to `paf` instead of `paf23`

### ISSUE THREAD

**Issue by ll7** [una-auxme/paf#283]

**Comment by ll7** [comment]
should be done while working on #278

**Comment by ll7** [comment]
- [ ] agent naming is wrong in agent.py

**Comment by ll7** [comment]
- [ ] Rename Repo
- [ ] CICD Runner
- [ ] coderabbit
- [ ] Find/replace
- [ ] Package check - Carla leaderboard image
- [ ] Projekt has wrong name

**Comment by JulianTrommer** [comment]
Package naming is moved to #309
