### ISSUE TITLE
[Feature]: Add automatic code formatting

### ISSUE THREAD

**Issue by JulianTrommer** [una-auxme/paf#289]

**Comment by ll7** [comment]
> ChatGPT

There are several popular code formatters for Python, each with its own strengths. The "best" one depends on your specific needs and preferences. Here are some of the most widely used auto-formatters for Python 3:

### 1. **Black**
   - **Philosophy**: "Black is the uncompromising Python code formatter." It formats code in a consistent way and prioritizes readability.
   - **Features**:
     - Opinionated: It has very few configuration options, which ensures consistency.
     - Fast: It’s optimized for speed.
     - Well-maintained and widely adopted in the Python community.
     - **Drawback**: Since it's highly opinionated, it may enforce formatting decisions you might not agree with.
   - **Command**: `black your_code.py`

### 2. **autopep8**
   - **Philosophy**: Fixes PEP 8 style guide violations.
   - **Features**:
     - Based on PEP 8, the official Python style guide.
     - Customizable: You can configure which PEP 8 rules to apply or ignore.
     - Ideal if you want to strictly follow PEP 8.
     - **Drawback**: It may not catch every stylistic issue compared to Black.
   - **Command**: `autopep8 --in-place your_code.py`

### 3. **YAPF (Yet Another Python Formatter)**
   - **Philosophy**: Tries to emulate the behavior of clang-format by reformatting code to the best formatting that conforms to style guides.
   - **Features**:
     - Flexible: It supports multiple formatting styles, including PEP 8 and custom styles.
     - You can configure it more easily compared to Black.
     - **Drawback**: Its output may not be as consistent as Black's, and it can sometimes be slower.
   - **Command**: `yapf -i your_code.py`

### 4. **isort**
   - **Philosophy**: Focuses specifically on sorting and organizing imports.
   - **Features**:
     - Ensures import statements are ordered alphabetically and grouped logically.
     - Can be combined with other formatters like Black for full code formatting.
     - **Drawback**: It only handles import sorting, so it needs to be paired with another tool for formatting the rest of the code.
   - **Command**: `isort your_code.py`

### 5. **Docformatter**
   - **Philosophy**: Focuses on formatting docstrings to match PEP 257.
   - **Features**:
     - Ensures that your docstrings are properly formatted and adhere to PEP 257 standards.
     - Useful when writing or maintaining extensive documentation in code.
   - **Command**: `docformatter your_code.py`

### Which one to choose?
   - **Black**: Best if you want a simple, consistent, and opinionated formatter.
   - **autopep8**: Best if you strictly follow PEP 8 and want more control.
   - **YAPF**: Best if you need a highly configurable formatter with custom style support.
   - **isort**: Best for managing and formatting imports specifically.
   - **Docformatter**: Best for cleaning up docstrings.

Many developers use **Black** in combination with **isort** for import sorting and sometimes **docformatter** for docstring consistency.

**Comment by ll7** [comment]
https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html

**Comment by ll7** [comment]
https://peps.python.org/pep-0008/#indentation

**Comment by JulianTrommer** [comment]
We decided to use black as a code formatter.
We also intend to add a GitHub action to check if the submitted code is different from the output of black.
This action should be required to pass for merging.

Since the actions and their settings will be changed in this issue we also intend to separate the build and drive action for a better structure.
