### ISSUE TITLE
[Feature]: Remove the Project and focus on a milestone based management?

### ISSUE THREAD

**Issue by ll7** [una-auxme/paf#294]

**Comment by ll7** [comment]
If we remove the project, we should archive the project.
Furthermore, we should remove the action that adds issue to the project. https://github.com/una-auxme/paf23/blob/main/.github/workflows/add-to-project.yml

**Comment by ll7** [comment]
I believe there are currently no downsides to maintaining the project. Therefore, we should continue with it until there is a clear reason or desire to remove it.

However, we should clarify whether we are using labels for priority or the specific priorities within the project. I believe using labels would be more straightforward. Do you agree @JulianTrommer ?

**Comment by JulianTrommer** [comment]
We decided that we use labels for priorities.
