### ISSUE TITLE
Template for planning future work

### ISSUE THREAD

**Issue by RoyaLxPole** [una-auxme/paf#448]
### Detailed Description
First find a good solution that all members of paf can work on a template.
Create a template what the teams can use to insert their problems for a general overview.
Discussion about this template with all teamleaders.
Be on hold if the teams have problems and check if all is working fine

### Definition of Done

create a template
template is accepted by all SEs and teamleaders
make it available for all

### Effort Estimate

overall 10h
Research 2h
create Template 3h
discussion with teamleader 3h
help with problems 2h

### Testability

not required

### Dependencies

all teams

**Comment by ll7** [comment]
Are you going to use draw.io to track your problems, or did I misunderstand your approach?

**Comment by RoyaLxPole** [comment]
I understood the discussion on Monday to mean that we should create an overview of the problems, divided into larger problems, which should then be broken down into smaller problems. I then looked for a suitable tool to work on this task. In addition, maintaining the graph would make it much easier to identify problems and, if necessary, assign them to a higher-level problem. The Perception team has gone one step further and has already drawn a roadmap on the Draw.io board.
