### ISSUE TITLE
Add radar sensor

### ISSUE THREAD

**Issue by Lukasnol** [una-auxme/paf#466]
### Detailed Description

create radar node.

### Definition of Done

- see above

**Comment by ll7** [comment]
Do you need a node to add a sensor, or do you need to adapt the sensor config file?

**Comment by Toni2go** [comment]
By "sensor config file" do you mean the file paf/code/agent/src/agent/agent.py? I think the radar sensor is already configured there, right?
The idea was to create a node similar to lidar_distance.py, so in this node we would subscribe to the RADAR topic and only publish the data important to us like distance, velocity, ...

**Comment by ll7** [comment]
Okay, so you are thinking about a radar measurement processing node. Yes, that would be helpful. 👍
